data_setup:
    no_time_series_fit: false
    trn_n: 3
    tst_n: 1
    addtnl_inputs: [sym, time]
    use_extra: true

model_pipeline:
    -
        name: sym_fit
        output_col: target
        klass_module: algs.split_combine_estimator
        klass_class: SplitEstimator
        params:
            clf_params:
                split_on: sym
                name: ss
                klass_module: algs.lp
                klass_class: LP
                params:
                    inputs: [p00,p01,p02,p03,p04,p05,p06,p07,p08,p09,p10,p11,p12,p13,p14,p15,p16,p17,p18,x00,x01,x02,x03,x04,x05,x06,x07,x08,x09,time,bs_spcfc,bs]
                    cv_params:
                        min_samples_leaf:
                            min: 1
                            max: 1000
                            type: int
        # dump_file: sym_preds.txt
