data_setup:
    no_time_series_fit: false
    trn_n: 3
    tst_n: 1
    addtnl_inputs: [sym,time]
    use_extra: true

model_pipeline:
    -
        name: sym_fit
        output_col: target
        clf:
            class: SplitEstimator
            params:
                # 'split_on' is an argument to SplitEstimator.__init__()
                split_on: sym
                # 'split_clf' is an argument to SplitEstimator.__init__()
                # does each model split optimize its own params? (sym='ABC' gets different params than sym='DEF'?)
                split_clf:
                    class: LP

