ignore_ftp:
    host: ftp.texasvanbavel.com
    user: johnp
    pw: dataminer123!
    path_root: farsight/

data_setup:
    no_time_series_fit: false
    trn_n: 3
    tst_n: 1
    addtnl_inputs: [sym,time]
    use_extra: true

model_pipeline:
    -
        name: grp_fit
        klass: 
            klass: RF
            clf_params:
                n_estimators: 64
            cv_params:
                min_samples_leaf:
                    min: 1
                    max: 1000
                    type: int
        output_col: target
        dump_file: grp_preds.txt
        
    -
        name: sym_fit
        output_col: target
        klass:
            klass: SplitEstimator
            clf_params:
                # 'split_on' is an argument to SplitEstimator.__init__()
                split_on: sym
                # 'split_model' is an argument to SplitEstimator.__init__()
                # does each model split optimize its own params? (sym='ABC' gets different params than sym='DEF'?)
                split_model:
                    klass: LP
                    cv_params:
                        min_samples_leaf:
                            min: 1
                            max: 1000
                            type: int
        dump_file: sym_preds.txt
